version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/London
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mosquitto

  home-automation-backend:
    build: ./backend
    container_name: home-automation-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - DATABASE_URL=file:./data/dev.db
    volumes:
      - ./data:/app/data
    depends_on:
      - mosquitto

  home-automation-frontend:
    build: ./frontend
    container_name: home-automation-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - home-automation-backend